-- EvalOtter seed data — generated by scripts/seed/generate-sql.ts
-- Equivalent to `npm run seed`. Idempotent: safe to re-run.
-- 29 assessments from scripts/seed/data/*.json
-- Run AFTER the schema migrations (supabase/combined_migrations.sql).
-- palmistry — file 20 of 29. Self-contained: its
-- category, its own questions, then the assessment itself.
-- Safe to re-run on its own.

begin;
insert into assessment_categories (key, label, icon, "order") values ('self-discovery', 'Self Discovery', 'hand', 9)
  on conflict (key) do update set label = excluded.label, icon = excluded.icon, "order" = excluded."order";

insert into questions (external_key, question_type, question_text, instructions, media, correct_answer, score_config, difficulty, category, tags, time_limit_seconds, required) values ('palmistry-01', ('multiple_choice')::question_type, 'Which hand do you write with?', 'Traditionally the dominant hand is read for present/future tendencies, and the other for innate traits.', ('[]')::jsonb, NULL, ('[]')::jsonb, ('easy')::assessment_difficulty, 'palmistry', '{}'::text[], NULL, true)
  on conflict (external_key) do update set question_type = excluded.question_type, question_text = excluded.question_text, instructions = excluded.instructions, media = excluded.media, correct_answer = excluded.correct_answer, score_config = excluded.score_config, difficulty = excluded.difficulty, category = excluded.category, tags = excluded.tags, time_limit_seconds = excluded.time_limit_seconds, required = excluded.required;
delete from question_options where question_id = (select id from questions where external_key = 'palmistry-01');
insert into question_options (question_id, label, value, image_url, is_correct, "order", score_config) values
  ((select id from questions where external_key = 'palmistry-01'), 'Right hand', 'right', NULL, NULL, 0, ('[]')::jsonb),
  ((select id from questions where external_key = 'palmistry-01'), 'Left hand', 'left', NULL, NULL, 1, ('[]')::jsonb),
  ((select id from questions where external_key = 'palmistry-01'), 'Both / ambidextrous', 'both', NULL, NULL, 2, ('[]')::jsonb);

insert into questions (external_key, question_type, question_text, instructions, media, correct_answer, score_config, difficulty, category, tags, time_limit_seconds, required) values ('palmistry-02', ('multiple_choice')::question_type, 'What are you most curious about right now?', NULL, ('[]')::jsonb, NULL, ('[]')::jsonb, ('easy')::assessment_difficulty, 'palmistry', '{}'::text[], NULL, true)
  on conflict (external_key) do update set question_type = excluded.question_type, question_text = excluded.question_text, instructions = excluded.instructions, media = excluded.media, correct_answer = excluded.correct_answer, score_config = excluded.score_config, difficulty = excluded.difficulty, category = excluded.category, tags = excluded.tags, time_limit_seconds = excluded.time_limit_seconds, required = excluded.required;
delete from question_options where question_id = (select id from questions where external_key = 'palmistry-02');
insert into question_options (question_id, label, value, image_url, is_correct, "order", score_config) values
  ((select id from questions where external_key = 'palmistry-02'), 'Career and ambition', 'career', NULL, NULL, 0, ('[]')::jsonb),
  ((select id from questions where external_key = 'palmistry-02'), 'Relationships and connection', 'relationships', NULL, NULL, 1, ('[]')::jsonb),
  ((select id from questions where external_key = 'palmistry-02'), 'Personal growth and self-understanding', 'growth', NULL, NULL, 2, ('[]')::jsonb),
  ((select id from questions where external_key = 'palmistry-02'), 'Just curious — no particular focus', 'open', NULL, NULL, 3, ('[]')::jsonb);

insert into questions (external_key, question_type, question_text, instructions, media, correct_answer, score_config, difficulty, category, tags, time_limit_seconds, required) values ('palmistry-03', ('multiple_choice')::question_type, 'How would you describe where you are in life right now?', NULL, ('[]')::jsonb, NULL, ('[]')::jsonb, ('easy')::assessment_difficulty, 'palmistry', '{}'::text[], NULL, true)
  on conflict (external_key) do update set question_type = excluded.question_type, question_text = excluded.question_text, instructions = excluded.instructions, media = excluded.media, correct_answer = excluded.correct_answer, score_config = excluded.score_config, difficulty = excluded.difficulty, category = excluded.category, tags = excluded.tags, time_limit_seconds = excluded.time_limit_seconds, required = excluded.required;
delete from question_options where question_id = (select id from questions where external_key = 'palmistry-03');
insert into question_options (question_id, label, value, image_url, is_correct, "order", score_config) values
  ((select id from questions where external_key = 'palmistry-03'), 'In a period of change or transition', 'transition', NULL, NULL, 0, ('[]')::jsonb),
  ((select id from questions where external_key = 'palmistry-03'), 'Settled and steady', 'settled', NULL, NULL, 1, ('[]')::jsonb),
  ((select id from questions where external_key = 'palmistry-03'), 'Building toward something new', 'building', NULL, NULL, 2, ('[]')::jsonb),
  ((select id from questions where external_key = 'palmistry-03'), 'Reflecting on the past', 'reflecting', NULL, NULL, 3, ('[]')::jsonb);

insert into questions (external_key, question_type, question_text, instructions, media, correct_answer, score_config, difficulty, category, tags, time_limit_seconds, required) values ('palmistry-04', ('text_input')::question_type, 'Anything specific you''d like your reading to touch on? (optional)', NULL, ('[]')::jsonb, NULL, ('[]')::jsonb, ('easy')::assessment_difficulty, 'palmistry', '{}'::text[], NULL, false)
  on conflict (external_key) do update set question_type = excluded.question_type, question_text = excluded.question_text, instructions = excluded.instructions, media = excluded.media, correct_answer = excluded.correct_answer, score_config = excluded.score_config, difficulty = excluded.difficulty, category = excluded.category, tags = excluded.tags, time_limit_seconds = excluded.time_limit_seconds, required = excluded.required;
delete from question_options where question_id = (select id from questions where external_key = 'palmistry-04');

-- palmistry (palmistry.json)
insert into assessments (slug, title, short_description, long_description, icon, category_id, engine_type, difficulty, estimated_duration_minutes, question_count, featured, access, status) values ('palmistry', 'Palmistry', 'Photograph both palms and receive a personalised, AI-generated reading. Entertainment and self-reflection only.', 'Palmistry works differently from a standard questionnaire: you photograph both palms with an on-screen hand-position guide, answer a few contextual questions, and receive a personalised AI-generated reading covering your heart line, head line, life line, fate line, hand shape, finger proportions, palm mounts, and other visible markers. This is offered purely for entertainment and self-reflection — it carries no scientific validity claim, is not a psychological or medical assessment, and never contributes to your EvalOtter cognitive score.', 'hand', (select id from assessment_categories where key = 'self-discovery'), ('vision_analysis')::assessment_engine_type, ('easy')::assessment_difficulty, 5, 4, false, ('free')::assessment_access, ('published')::assessment_status)
  on conflict (slug) do update set title = excluded.title, short_description = excluded.short_description, long_description = excluded.long_description, icon = excluded.icon, category_id = excluded.category_id, engine_type = excluded.engine_type, difficulty = excluded.difficulty, estimated_duration_minutes = excluded.estimated_duration_minutes, question_count = excluded.question_count, featured = excluded.featured, access = excluded.access, status = excluded.status;
delete from result_ranges where assessment_id = (select id from assessments where slug = 'palmistry');
delete from brain_profile_contribution_rules where assessment_id = (select id from assessments where slug = 'palmistry');
insert into assessment_versions (assessment_id, version_number, status, settings, published_at)
  select a.id, coalesce((select max(v.version_number) from assessment_versions v where v.assessment_id = a.id), 0) + 1, 'published'::assessment_status, ('{"allowBackNavigation":true,"randomizeSections":false,"randomizeQuestions":false,"randomizeAnswerOrder":false,"showProgressBar":true,"showInstructionsBetweenSections":true,"autosaveIntervalSeconds":10,"totalTimeLimitSeconds":null}')::jsonb, now()
  from assessments a where a.slug = 'palmistry';
update assessments set current_version_id = (select v.id from assessment_versions v where v.assessment_id = assessments.id order by v.version_number desc limit 1) where slug = 'palmistry';
insert into assessment_sections (assessment_version_id, name, description, instructions, time_limit_seconds, randomize_questions, weight, "order") values ((select current_version_id from assessments where slug = 'palmistry'), 'About You', 'A few questions to personalise your reading.', 'These help tailor the AI-generated reading to you — there are no right or wrong answers.', NULL, false, 1, 1);
insert into assessment_questions (assessment_version_id, section_id, question_id, "order", weight) values
  ((select current_version_id from assessments where slug = 'palmistry'), (select id from assessment_sections where assessment_version_id = (select current_version_id from assessments where slug = 'palmistry') and name = 'About You'), (select id from questions where external_key = 'palmistry-01'), 0, 1),
  ((select current_version_id from assessments where slug = 'palmistry'), (select id from assessment_sections where assessment_version_id = (select current_version_id from assessments where slug = 'palmistry') and name = 'About You'), (select id from questions where external_key = 'palmistry-02'), 1, 1),
  ((select current_version_id from assessments where slug = 'palmistry'), (select id from assessment_sections where assessment_version_id = (select current_version_id from assessments where slug = 'palmistry') and name = 'About You'), (select id from questions where external_key = 'palmistry-03'), 2, 1),
  ((select current_version_id from assessments where slug = 'palmistry'), (select id from assessment_sections where assessment_version_id = (select current_version_id from assessments where slug = 'palmistry') and name = 'About You'), (select id from questions where external_key = 'palmistry-04'), 3, 1);
commit;
