import {
  Brain,
  GitBranch,
  Sparkles,
  MessageSquare,
  Hand,
  HeartHandshake,
  Calculator,
  Box,
  BookOpen,
  Palette,
  Map,
  Ear,
  Eye,
  Layers,
  Compass,
  FileText,
  Users,
  RotateCw,
  Volume2,
  Timer,
  Target,
  Zap,
  Shuffle,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  brain: Brain,
  "git-branch": GitBranch,
  sparkles: Sparkles,
  "message-square": MessageSquare,
  hand: Hand,
  "heart-handshake": HeartHandshake,
  calculator: Calculator,
  box: Box,
  "book-open": BookOpen,
  palette: Palette,
  map: Map,
  ear: Ear,
  eye: Eye,
  layers: Layers,
  compass: Compass,
  "file-text": FileText,
  users: Users,
  "rotate-cw": RotateCw,
  "volume-2": Volume2,
  timer: Timer,
  target: Target,
  zap: Zap,
  shuffle: Shuffle,
};

export function AssessmentIcon({ icon, className }: { icon: string; className?: string }) {
  const Icon = ICONS[icon] ?? Brain;
  return <Icon className={className} />;
}
